services:
  price:
    container_name: price
    image: harbor.wws741.top/mcp-rpc/price:latest
    build:
      context: ../..
      dockerfile: services/price/Dockerfile
    ports:
      - 50001:8080
    volumes:
      - ./etc:/app/etc
