services:
  rsi:
    image: harbor.wws741.top/mcp-rpc/rsi:latest
    build:
      context: ../..
      dockerfile: services/rsi/Dockerfile
    ports:
      - 50002:8080
    volumes:
      - ./etc:/app/etc
